### ISSUE TITLE
BUG: Metadata inference issue with named geometry column

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#100]
If you create dask GeoDataFrame from a geopandas gdf with geometry column name different than "geometry", calling `.geometry` in `map_partitions` raises an attribute error. With `"geometry"` name the same code is fine.

```py
import geopandas as gpd
import dask_geopandas

df = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres")).rename_geometry("geom")
ddf = dask_geopandas.from_geopandas(df, npartitions=4)

def get_geometry(partition):
    return partition.geometry

ddf.map_partitions(get_geometry)
```
```py
ValueError: Metadata inference failed in `get_geometry`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'GeoDataFrame' object has no attribute 'geometry'")

Traceback:
---------
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py", line 5672, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/var/folders/kp/fxnnw89x5qbb9gryn507p03c0000gn/T/ipykernel_52968/1774662833.py", line 2, in get_geometry
    return partition.geometry
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/pandas/core/generic.py", line 5478, in __getattr__
    return object.__getattribute__(self, name)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175     try:
--> 176         yield
    177     except Exception as e:

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5671     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5672         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5673 

/var/folders/kp/fxnnw89x5qbb9gryn507p03c0000gn/T/ipykernel_52968/1774662833.py in get_geometry(partition)
      1 def get_geometry(partition):
----> 2     return partition.geometry
      3 ddf.map_partitions(get_geometry)

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5477             return self[name]
-> 5478         return object.__getattribute__(self, name)
   5479 

AttributeError: 'GeoDataFrame' object has no attribute 'geometry'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/var/folders/kp/fxnnw89x5qbb9gryn507p03c0000gn/T/ipykernel_52968/1774662833.py in <module>
      1 def get_geometry(partition):
      2     return partition.geometry
----> 3 ddf.map_partitions(get_geometry)

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    704         None as the division.
    705         """
--> 706         return map_partitions(func, self, *args, **kwargs)
    707 
    708     @insert_meta_param_description(pad=12)

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, *args, **kwargs)
   5726         # Use non-normalized kwargs here, as we want the real values (not
   5727         # delayed values)
-> 5728         meta = _emulate(func, *args, udf=True, **kwargs)
   5729     else:
   5730         meta = make_meta(meta, index=meta_index, parent_meta=parent_meta)

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5670     """
   5671     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5672         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5673 
   5674 

/opt/miniconda3/envs/geo_dev/lib/python3.9/contextlib.py in __exit__(self, type, value, traceback)
    133                 value = type()
    134             try:
--> 135                 self.gen.throw(type, value, traceback)
    136             except StopIteration as exc:
    137                 # Suppress StopIteration *unless* it's the same exception that

/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    195         )
    196         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 197         raise ValueError(msg) from e
    198 
    199 

ValueError: Metadata inference failed in `get_geometry`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'GeoDataFrame' object has no attribute 'geometry'")

Traceback:
---------
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/dask/dataframe/core.py", line 5672, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/var/folders/kp/fxnnw89x5qbb9gryn507p03c0000gn/T/ipykernel_52968/1774662833.py", line 2, in get_geometry
    return partition.geometry
  File "/opt/miniconda3/envs/geo_dev/lib/python3.9/site-packages/pandas/core/generic.py", line 5478, in __getattr__
    return object.__getattribute__(self, name)
```

**Comment by jorisvandenbossche** [comment]
So the issue seems to be due to an incorrect `_meta_nonempty`, which is used here for testing the applied function on "meta". The `_meta` property is constructed fine, but the generated `_meta_nonempty` is not:

```
In [2]: ddf._meta_nonempty
/home/joris/scipy/repos/dask-geopandas/dask_geopandas/backends.py:60: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
  return geopandas.GeoDataFrame(df, crs=x.crs)#geometry=x._geometry_column_name, crs=x.crs)
Out[2]: 
   pop_est continent name iso_a3  gdp_md_est                                           geom
0        1       foo  foo    foo         1.0  LINESTRING (0.00000 0.00000, 0.00000 1.00000)
1        1       foo  foo    foo         1.0  LINESTRING (1.00000 1.00000, 1.00000 2.00000)

In [3]: ddf._meta_nonempty.geometry
...
AttributeError: No geometry data set yet (expected in column 'geometry'.)

In [4]: ddf._meta_nonempty._geometry_column_name
Out[4]: 'geometry'
```
