### ISSUE TITLE
BUG: IO read multiple files using wildcard

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/dask-geopandas#168]
Edit: sorry typo! Closing

Tested on latest:

```
mamba create -n test_env python=3.9 --y && conda activate test_env
pip install git+https://github.com/geopandas/dask-geopandas
pip install --extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre pyarrow
```

```
from datetime import datetime
import dask_geopandas as dgpd
import geopandas as gpd

# Write naturalearth_lowres.parquet using geopandas
gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
gdf["date"] = datetime(2022, 1, 1)
gdf.to_parquet("naturalearth_lowres_2021-01-01.parquet")
gdf["date"] = datetime(2022, 1, 2)
gdf.to_parquet("naturalearth_lowres_2021-01-02.parquet")

dgpd.read_parquet("naturalearth_lowres_2022-01-*.parquet")

>>> dgpd.read_parquet("naturalearth_lowres_2022-01-*.parquet")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 93, in read_parquet
    result = dd.read_parquet(*args, engine=GeoArrowEngine, **kwargs)
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 400, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 51, in read_metadata
    meta, stats, parts, index = super().read_metadata(fs, paths, **kwargs)
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask/dataframe/io/parquet/arrow.py", line 387, in read_metadata
    meta = cls._create_dd_meta(dataset_info)
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 84, in _create_dd_meta
    meta = cls._update_meta(meta, schema)
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 68, in _update_meta
    return _update_meta_to_geodataframe(meta, schema.metadata)
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/dask_geopandas/io/arrow.py", line 35, in _update_meta_to_geodataframe
    raise ValueError(
ValueError: Missing geo metadata in the Parquet/Feather file. Use dask.dataframe.read_parquet/pandas.read_feather() instead.
```

I remember it works for simple cases https://twitter.com/RayBell_DTN/status/1460708895345754120?s=20&t=DRtav5f-Ezto4Emum_Ghsw

**Comment by jorisvandenbossche** [comment]
But, it is a bit a confusing error message, I think?

Because the result of the typo is that you would have an empty result, or an error message about that there is no data to get the geo metadata from. 

When reading the same with dask, you indeed get an empty dataframe:

```
In [13]: dd.read_parquet("naturalearth_lowres_2022-01-*.parquet")
Out[13]: 
Empty Dask DataFrame Structure:
Columns: []
Divisions: [, ]
Dask Name: read-parquet, 1 tasks
```

For dask-geopandas it is harder to return an empty dataframe (no information about the geometry column or crs).
