### ISSUE TITLE
read parquet from s3 failing with 'GeoArrowEngine' has no attribute 'extract_filesystem'

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/dask-geopandas#250]
We have nightly testing of reading geoparquet in our s3 buckets (using intake-geopandas). This started failing with the release of dask 2023.4.0 cc. @jrbourbeau.

I try and update this if I can find a geoparquet hosted on a public s3 bucket.

Create new environment:
`mamba create -n test_env python=3.10 --y && conda activate test_env`

Install dask-geopandas and s3fs:
`pip install dask-geopandas s3fs`

open a (geo)parquet:
```
import dask_geopandas as dgpd
dgpd.read_parquet("s3://BUCKET/FILE.parquet")
```

```
Traceback (most recent call last):
  File "/opt/userenvs/ray.bell/test_env/lib/python3.10/site-packages/dask/backends.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/opt/userenvs/ray.bell/test_env/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py", line 519, in read_parquet
    fs, paths, dataset_options, open_file_options = engine.extract_filesystem(
AttributeError: type object 'GeoArrowEngine' has no attribute 'extract_filesystem'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/userenvs/ray.bell/test_env/lib/python3.10/site-packages/dask_geopandas/io/parquet.py", line 111, in read_parquet
    result = dd.read_parquet(*args, engine=GeoArrowEngine, **kwargs)
  File "/opt/userenvs/ray.bell/test_env/lib/python3.10/site-packages/dask/backends.py", line 137, in wrapper
    raise type(e)(
AttributeError: An error occurred while calling the read_parquet method registered to the pandas backend.
Original Message: type object 'GeoArrowEngine' has no attribute 'extract_filesystem'
```

**Comment by jrbourbeau** [comment]
Thanks @raybellwaves. I wonder if this is a duplicate of https://github.com/geopandas/dask-geopandas/issues/241?

> This started failing with the release of dask 2023.4.0 three days ago

I'm not aware of any related changes in this release. The `extract_filesystem` method in the traceback was added several releases ago (xref https://github.com/dask/dask/pull/9699). 

Also, as Joris mentioned here https://github.com/geopandas/dask-geopandas/issues/241#issuecomment-1475862668, I would expect `GeoArrowEngine` to have an `extract_filesystem` method regardless since it subclasses the arrow parquet engine in `dask`

**Comment by jtmiclat** [comment]
Cross posting from the other thread https://github.com/geopandas/dask-geopandas/issues/241#issuecomment-1555095541


=======
hi! i was able to look into this! if pyarrow is not installed then the inheritances falls apart because of the fallback import.
https://github.com/geopandas/dask-geopandas/blob/d3e15d1efb5a9a6c74a13f933ea2d84196992fac/dask_geopandas/io/parquet.py#L15-L22


 I think some envs default to have pyarrow so you really need a clean env  to test this. A solution to this is to throw an import error/warning when instantiating GeoArrowEngine if pyarrow was not properly imported.
 
 
 To reiterate 
 
 this fails
```
pip install dask dask-geopandas 
```
this works
```
pip install dask dask-geopandas  pyarrow
# or 
pip install dask[complete] dask-geopandas
```
