### ISSUE TITLE
Error when importing dask_geopandas.expr on Python 3.10 when Dask query planning is disabled

### ISSUE THREAD

**Issue by maximlt** [geopandas/dask-geopandas#311]
The test runs of datashader have been failing recently on Python 3.10 and the issue can be narrowed down to this piece of code:

```python
import dask
dask.config.set({'dataframe.query-planning': False})

import dask_geopandas.expr
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/mliquet/dev/datashader/.mltmess/debuglayout.py", line 3, in <module>
    import dask_geopandas.expr
  File "/Users/mliquet/dev/datashader/.pixi/envs/test-310/lib/python3.10/site-packages/dask_geopandas/expr.py", line 587, in <module>
    class GeoSeries(_Frame, dd.Series):
TypeError: multiple bases have instance lay-out conflict
```

I just wanted to report it in case someone else stumbles upon that weird corner case, we're going to slightly modify datashader to deal with that case directly. Feel free to close the issue!

**Comment by jorisvandenbossche** [comment]
Searching online for the error, some comments point to this issue appearing when adding `__slots__` to the shared base class (see eg comment on answer in https://stackoverflow.com/questions/48136025/typeerror-multiple-bases-have-instance-lay-out-conflict). 

And indeed, it seems that slots were introduced (at least non-empty slots) in `DaskMethodsMixin` (which both of the classes we inherit from have as their base class as well) in https://github.com/dask/dask/pull/11348. So that might be related.

Downgrading dask to 2024.7, then the error goes away (although when upgrading dask in my dev env, I still cannot reproduce the error there, so it's not just the dask version that is in play .. Upgrading Python to 3.11 in the test env, then the error also goes away, so it's specific to Python 3.10?)

**Comment by jorisvandenbossche** [comment]
Given that this only seems to happen for Python 3.10, when explicitly importing `dask_geopandas.expr` when query planning is disabled (a normal import of `dask_geopandas` will not import that in this case), and dask-cudf has the same code organization (and that I am not sure how to fix this), it's maybe not too important?

@maximlt what was the use case in datashader to explicitly import `dask_geopandas.expr`?

**Comment by holoviz-developers** [comment]
Thanks for digging into that :) 

> it's maybe not too important?

That's also my conclusion.

It's part of an `isinstance` check https://github.com/holoviz/datashader/blob/e9e64c5c2b845fe2d815c221437b5399f5e2e2e1/datashader/core.py#L1292

**Comment by maximlt** [comment]
Thanks for digging into that :) 

> it's maybe not too important?

That's also my conclusion.

It's part of an `isinstance` check https://github.com/holoviz/datashader/blob/e9e64c5c2b845fe2d815c221437b5399f5e2e2e1/datashader/core.py#L1292

**Comment by jorisvandenbossche** [comment]
> It's part of an `isinstance` check https://github.com/holoviz/datashader/blob/e9e64c5c2b845fe2d815c221437b5399f5e2e2e1/datashader/core.py#L1292

Would it be sufficient for datashader to just do `dask_geopandas import GeoDataFrame`, instead of importing from both `dask_geopandas.core` and `dask_geopandas.expr`. That will then automatically give you one of both depending on the dask setting (of course, that might then not work if the user changes that setting after this code is run?)
